apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mmorpg-framework.fullname" . }}
  labels:
    {{- include "mmorpg-framework.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.app.config.apiKey | b64enc | quote }}
